"use client";
import type { Metadata } from "next";

import { Montserrat } from "next/font/google";

const nunit = Montserrat({
  subsets: ["latin"],
});

import "./globals.css";
import Navbar from "@/components/header/navbar";
import FastClick from "@/components/fastClick/fastClick";
import Footer from "@/components/footer";
import dynamic from "next/dynamic";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const DynamicNavbar = dynamic(() => import("@/components/header/navbar"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunit.className}>
        <DynamicNavbar />
        <FastClick />
        {children}
        <Footer />
      </body>
    </html>
  );
}
